name: Hızlı Takip Botu

on:
  schedule:
    - cron: '*/5 * * * *'  # 5 dakikada bir tetikler
  workflow_dispatch:      # Elle tetikleme butonu

permissions:
  contents: write         # Dosya kaydetme izni

jobs:
  calistir:
    runs-on: ubuntu-latest

    steps:
      - name: Depoyu Çek
        uses: actions/checkout@v3

      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Kütüphaneleri Yükle
        run: |
          pip install requests beautifulsoup4

      - name: Botu Çalıştır
        env: 
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python ptakip.py

      - name: Değişikliği Kaydet
        run: |
          git config --global user.name 'GitHub Action Bot'
          git config --global user.email 'bot@github.com'
          git add son_durum.txt
          git diff --quiet && git diff --staged --quiet || (git commit -m "Güncelleme" && git push)
